In [1]:
import pandas as pd
import sqlalchemy as db
from sqlalchemy import text

In [2]:
import sys
print(sys.executable)

c:\Users\57314\anaconda3\python.exe

In [ ]:
engine = db.create_engine("mysql+mysqlconnector://root:root@127.0.0.1:3310/db_movies_netflix_transact")
conn = engine.connect()

ModuleNotFoundError: No module named 'MySQLdb'

# Cargamos datos a la dimension Movie

In [6]:
query = """
SELECT 
    movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate, 
    gender.name as gender , person.name as participantName, participant.participantRole as roleparticipant 
FROM movie 
INNER JOIN participant 
ON movie.movieID=participant.movieID
INNER JOIN person
ON person.personID = participant.personID
INNER JOIN movie_gender 
ON movie.movieID = movie_gender.movieID
INNER JOIN gender 
ON movie_gender.genderID = gender.genderID
"""

In [7]:
movies_data=pd.read_sql(query, con=conn) 
movies_data["movieID"]=movies_data["movieID"].astype('int')
movies_data

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [8]:
movies_award=pd.read_csv("./data/Awards_movie.csv")
movies_award["movieID"]=movies_award["movieID"].astype('int')
movies_award.rename(columns={"Aware":"Award"}, inplace=True)
movies_award

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [9]:
movie_data=pd.merge(movies_data,movies_award, left_on="movieID", right_on="movieID")
movie_data

,movieID,title,releaseDate,gender,participantName,roleparticipant,IdAward,Award
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [10]:
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/dw_netflix")
conn = engine.connect()

In [11]:

movie_data = movie_data.rename(columns={'releaseDate': 'releaseMovie', 'Award': 'awardMovie'})

In [12]:
movie_data = movie_data.drop(columns=['IdAward'])

In [13]:
movie_data.head()

,movieID,title,releaseMovie,gender,participantName,roleparticipant,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,Grammy

In [14]:
movie_data.to_sql('dimMovie',conn,if_exists='append', index=False)

3

In [15]:
pd.read_sql('dimMovie', con=conn)

,movieID,title,releaseMovie,gender,participantName,roleparticipant,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,Grammy

# Cargamos datos a la dimension USER

In [16]:
users = pd.read_csv("./data/users.csv", sep='|')
users

      idUser     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [17]:
users = users.rename(columns={'idUser': 'userID'})
users

      userID     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [18]:
users.to_sql('dimUser',conn,if_exists='append', index=False)

20

# Cargamos datos a la tabla de hechos

In [19]:
users_id=users["userID"]
movies_id=movies_data["movieID"]

In [20]:
watchs_data=pd.merge(users_id,movies_id, how="cross")
watchs_data

      userID   movieID
0    1002331  80192187
1    1002331  80210920
2    1002331  81157374
3    1002332  80192187
4    1002332  80210920
5    1002332  81157374
6    1002333  80192187
7    1002333  80210920
8    1002333  81157374
9    1002334  80192187
10   1002334  80210920
11   1002334  81157374
12   1002335  80192187
13   1002335  80210920
14   1002335  81157374
15   1002336  80192187
16   1002336  80210920
17   1002336  81157374
18   1002337  80192187
19   1002337  80210920
20   1002337  81157374
21   1002338  80192187
22   1002338  80210920
23   1002338  81157374
24   1002339  80192187
25   1002339  80210920
26   1002339  81157374
27  10023310  80192187
28  10023310  80210920
29  10023310  81157374
30  10023311  80192187
31  10023311  80210920
32  10023311  81157374
33  10023312  80192187
34  10023312  80210920
35  10023312  81157374
36  10023313  80192187
37  10023313  80210920
38  10023313  81157374
39  10023314  80192187
40  10023314  80210920
41  10023314  81157374
42  10023315  80192187
43  10023315  80210920
44  10023315  81157374
45  10023316  80192187
46  10023316  80210920
47  10023316  81157374
48  10023317  80192187
49  10023317  80210920
50  10023317  81157374
51  10023318  80192187
52  10023318  80210920
53  10023318  81157374
54  10023319  80192187
55  10023319  80210920
56  10023319  81157374
57  10023320  80192187
58  10023320  80210920
59  10023320  81157374

In [21]:
import random
from datetime import datetime, timedelta
import random

def gen_rating():
    # Generar un número aleatorio entre 0 y 5 con 1 solo decimal
    numero_aleatorio = round(random.uniform(0, 5), 1)
    # Mostrar el número aleatorio
    return numero_aleatorio

def gen_timestamp():
    # Generar un timestamp aleatorio dentro de un rango específico
    start_date = datetime(2024, 1, 15)
    end_date = datetime(2024, 4, 6)

    # Calcular un valor aleatorio entre start_date y end_date
    random_date = start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))

    # Mostrar el timestamp aleatorio
    return random_date

In [22]:
watchs_data["rating"]=watchs_data["movieID"].apply(lambda x: gen_rating())
watchs_data["timestamp"]=watchs_data["userID"].apply(lambda x: gen_timestamp())

In [23]:
watchs_data

      userID   movieID  rating           timestamp
0    1002331  80192187     3.4 2024-02-09 19:21:00
1    1002331  80210920     4.1 2024-03-21 09:19:36
2    1002331  81157374     1.6 2024-03-23 20:04:32
3    1002332  80192187     1.4 2024-03-15 10:27:01
4    1002332  80210920     4.2 2024-02-20 10:27:46
5    1002332  81157374     1.1 2024-03-10 05:06:50
6    1002333  80192187     0.5 2024-02-05 10:21:36
7    1002333  80210920     3.2 2024-02-29 12:14:28
8    1002333  81157374     3.4 2024-04-02 01:01:08
9    1002334  80192187     1.4 2024-03-11 16:31:22
10   1002334  80210920     3.6 2024-02-29 14:52:29
11   1002334  81157374     0.5 2024-01-15 00:37:10
12   1002335  80192187     2.1 2024-03-11 15:42:10
13   1002335  80210920     2.6 2024-03-07 11:58:46
14   1002335  81157374     4.8 2024-03-23 05:42:41
15   1002336  80192187     0.3 2024-01-25 13:02:01
16   1002336  80210920     0.6 2024-03-28 05:26:16
17   1002336  81157374     0.1 2024-04-03 06:33:13
18   1002337  80192187     3.2 2024-02-10 23:11:56
19   1002337  80210920     0.7 2024-01-28 03:51:15
20   1002337  81157374     1.6 2024-02-03 22:11:18
21   1002338  80192187     4.7 2024-03-15 03:45:50
22   1002338  80210920     3.9 2024-01-25 22:19:15
23   1002338  81157374     0.3 2024-02-14 22:59:21
24   1002339  80192187     2.1 2024-02-08 00:13:53
25   1002339  80210920     0.9 2024-01-21 10:10:03
26   1002339  81157374     2.8 2024-02-07 11:21:41
27  10023310  80192187     3.7 2024-01-25 10:22:17
28  10023310  80210920     2.9 2024-02-14 00:18:33
29  10023310  81157374     3.4 2024-03-08 11:39:42
30  10023311  80192187     1.6 2024-02-09 01:59:44
31  10023311  80210920     0.2 2024-02-29 07:17:58
32  10023311  81157374     1.0 2024-03-17 07:51:54
33  10023312  80192187     4.5 2024-02-16 18:33:49
34  10023312  80210920     4.5 2024-02-26 04:30:30
35  10023312  81157374     4.0 2024-02-11 01:43:24
36  10023313  80192187     1.5 2024-02-15 13:16:32
37  10023313  80210920     1.3 2024-03-30 03:12:25
38  10023313  81157374     4.1 2024-03-03 19:45:03
39  10023314  80192187     1.2 2024-01-29 08:20:45
40  10023314  80210920     2.5 2024-02-07 05:42:41
41  10023314  81157374     1.4 2024-03-26 06:40:06
42  10023315  80192187     1.9 2024-02-13 19:26:22
43  10023315  80210920     4.9 2024-03-06 15:33:40
44  10023315  81157374     0.8 2024-03-25 08:41:41
45  10023316  80192187     3.4 2024-01-17 07:05:02
46  10023316  80210920     1.7 2024-03-03 21:36:30
47  10023316  81157374     2.9 2024-04-02 03:02:27
48  10023317  80192187     1.9 2024-04-03 21:42:24
49  10023317  80210920     0.9 2024-02-17 02:17:50
50  10023317  81157374     0.6 2024-03-11 08:32:55
51  10023318  80192187     2.5 2024-02-21 02:24:12
52  10023318  80210920     4.1 2024-02-26 11:28:07
53  10023318  81157374     4.6 2024-03-25 12:38:19
54  10023319  80192187     2.6 2024-02-15 18:01:16
55  10023319  80210920     3.3 2024-01-29 00:12:51
56  10023319  81157374     4.7 2024-02-20 14:58:05
57  10023320  80192187     1.4 2024-02-13 09:08:16
58  10023320  80210920     2.8 2024-01-30 06:32:56
59  10023320  81157374     3.6 2024-01-24 16:23:32

In [24]:
# Cargamos tabla de hechos
watchs_data.to_sql("FactWatchs", conn, if_exists='append', index=False)

60

In [25]:
### SET FOREIGN_KEY_CHECKS = 0;
### SET FOREIGN_KEY_CHECKS = 1;